<?php
session_start();
require_once '../config/database.php';

// Check Admin Access
if (!isset($_SESSION['user_id']) || $_SESSION['user_role'] !== 'admin') {
    header('Location: dashboard.php');
    exit;
}

$page_title = 'Backup Database';
$page_subtitle = 'Quản lý sao lưu và phục hồi dữ liệu hệ thống';
$backup_dir = __DIR__ . '/backups/';

// Create directory if not exists
if (!file_exists($backup_dir)) {
    mkdir($backup_dir, 0755, true);
    // Create .htaccess to protect backups
    file_put_contents($backup_dir . '.htaccess', 'Deny from all');
}

$message = '';
$error = '';
$message_type = ''; // success, warning, error

// Helper: Format Size
function format_size($bytes)
{
    if ($bytes >= 1073741824)
        return number_format($bytes / 1073741824, 2) . ' GB';
    if ($bytes >= 1048576)
        return number_format($bytes / 1048576, 2) . ' MB';
    if ($bytes >= 1024)
        return number_format($bytes / 1024, 2) . ' KB';
    return $bytes . ' bytes';
}

// Handle Actions
if (isset($_GET['download']) && !empty($_GET['download'])) {
    $file = $backup_dir . basename($_GET['download']);
    if (file_exists($file)) {
        header('Content-Description: File Transfer');
        header('Content-Type: application/octet-stream');
        header('Content-Disposition: attachment; filename="' . basename($file) . '"');
        header('Expires: 0');
        header('Cache-Control: must-revalidate');
        header('Pragma: public');
        header('Content-Length: ' . filesize($file));
        readfile($file);
        exit;
    }
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $action = $_POST['action'] ?? '';

    if ($action === 'create_backup') {
        try {
            $db = getDB();
            $tables = [];
            $stmt = $db->query("SHOW TABLES");
            while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
                $tables[] = $row[0];
            }

            $content = "-- Aurora Hotel Plaza Database Backup\n";
            $content .= "-- Date: " . date('Y-m-d H:i:s') . "\n";
            $content .= "-- Generated by: " . $_SESSION['user_name'] . "\n\n";
            $content .= "SET FOREIGN_KEY_CHECKS=0;\n";
            $content .= "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n";
            $content .= "SET time_zone = \"+07:00\";\n\n";

            foreach ($tables as $table) {
                // Structure
                $stmt = $db->query("SHOW CREATE TABLE `$table`");
                $row = $stmt->fetch(PDO::FETCH_NUM);
                $content .= "-- Table structure for table `$table`\n";
                $content .= "DROP TABLE IF EXISTS `$table`;\n";
                $content .= $row[1] . ";\n\n";

                // Data
                $stmt = $db->query("SELECT * FROM `$table`");
                $rows = $stmt->fetchAll(PDO::FETCH_NUM);
                $count = count($rows);

                if ($count > 0) {
                    $content .= "-- Dumping data for table `$table`\n";
                    $content .= "INSERT INTO `$table` VALUES\n";

                    foreach ($rows as $i => $row) {
                        $content .= "(";
                        $fields = [];
                        foreach ($row as $field) {
                            if (is_null($field)) {
                                $fields[] = "NULL";
                            } else {
                                $field = addslashes($field);
                                $field = str_replace("\n", "\\n", $field);
                                $fields[] = "'" . $field . "'";
                            }
                        }
                        $content .= implode(',', $fields);
                        $content .= ")" . ($i < $count - 1 ? ",\n" : ";\n\n");
                    }
                }
            }

            $content .= "SET FOREIGN_KEY_CHECKS=1;\n";

            $filename = 'backup_' . date('Y-m-d_H-i-s') . '.sql';
            if (file_put_contents($backup_dir . $filename, $content)) {
                $message = "Đã tạo backup thành công: $filename";
                $message_type = 'success';

                // Log activity
                try {
                    $stmt = $db->prepare("INSERT INTO activity_logs (user_id, action, description, ip_address, created_at) VALUES (?, 'backup_create', ?, ?, NOW())");
                    $stmt->execute([$_SESSION['user_id'], "Đã tạo file backup: $filename", $_SERVER['REMOTE_ADDR']]);
                } catch (Exception $e) { /* ignore log error */
                }
            } else {
                $error = "Không thể ghi file backup. Vui lòng kiểm tra phân quyền.";
            }

        } catch (Exception $e) {
            $error = "Lỗi backup: " . $e->getMessage();
        }
    } elseif ($action === 'delete_backup') {
        $filename = basename($_POST['filename']);
        $file = $backup_dir . $filename;
        if (file_exists($file) && unlink($file)) {
            $message = "Đã xóa file backup: $filename";
            $message_type = 'success';

            // Log
            try {
                $db = getDB();
                $stmt = $db->prepare("INSERT INTO activity_logs (user_id, action, description, ip_address, created_at) VALUES (?, 'backup_delete', ?, ?, NOW())");
                $stmt->execute([$_SESSION['user_id'], "Đã xóa file backup: $filename", $_SERVER['REMOTE_ADDR']]);
            } catch (Exception $e) {
            }
        } else {
            $error = "Không thể xóa file.";
        }
    } elseif ($action === 'restore_backup') {
        $filename = basename($_POST['filename']);
        $file = $backup_dir . $filename;

        if (file_exists($file)) {
            try {
                $db = getDB();
                $db->setAttribute(PDO::ATTR_EMULATE_PREPARES, 0);

                $sql = file_get_contents($file);

                // Remove comments and split by semicolon
                // This is a basic splitter, might fail on complex stored procedures but ok for simple dumps
                // A better way is to rely on PDO exec for multiple statements if supported, or split carefully.
                // Since our dump format is simple (standard INSERTs), splitting by ";\n" or ensuring 1 statement per execution is safer.

                // Option 1: Execute full content if driver supports it (MySQL usually does allow multiple statements if config allows)
                // But PDO default might not. Let's try executing full script first.

                $db->exec($sql);

                $message = "Đã phục hồi dữ liệu từ file $filename thành công!";
                $message_type = 'success';

                // Log
                try {
                    $stmt = $db->prepare("INSERT INTO activity_logs (user_id, action, description, ip_address, created_at) VALUES (?, 'backup_restore', ?, ?, NOW())");
                    $stmt->execute([$_SESSION['user_id'], "Đã restore database từ file: $filename", $_SERVER['REMOTE_ADDR']]);
                } catch (Exception $e) {
                }

            } catch (Exception $e) {
                // If direct exec fails, try splitting
                $error = "Lỗi restore: " . $e->getMessage();
            }
        } else {
            $error = "File backup không tồn tại.";
        }
    }
}

// Get Data for View
$backups = [];
$files = glob($backup_dir . '*.sql');
if ($files) {
    foreach ($files as $file) {
        $backups[] = [
            'name' => basename($file),
            'size' => filesize($file),
            'date' => filemtime($file),
            'path' => $file
        ];
    }
    // Sort by date desc
    usort($backups, function ($a, $b) {
        return $b['date'] - $a['date'];
    });
}

include 'includes/admin-header.php';
?>

<div class="max-w-6xl mx-auto">

    <!-- Alerts -->
    <?php if ($message): ?>
        <div
            class="mb-6 p-4 rounded-xl border flex items-center gap-3 <?php echo $message_type === 'success' ? 'bg-green-50 border-green-200 text-green-700' : 'bg-blue-50 border-blue-200 text-blue-700'; ?>">
            <span class="material-symbols-outlined">check_circle</span>
            <p><?php echo $message; ?></p>
        </div>
    <?php endif; ?>

    <?php if ($error): ?>
        <div class="mb-6 p-4 rounded-xl border bg-red-50 border-red-200 text-red-700 flex items-center gap-3">
            <span class="material-symbols-outlined">error</span>
            <p><?php echo $error; ?></p>
        </div>
    <?php endif; ?>

    <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">

        <!-- Left Column: Actions & Info -->
        <div class="space-y-6">
            <!-- Create Backup Card -->
            <div class="card bg-gradient-to-br from-indigo-500 to-indigo-600 text-white border-none shadow-lg">
                <div class="p-6">
                    <div class="flex items-center gap-4 mb-4">
                        <div class="p-3 bg-white/20 rounded-xl backdrop-blur-sm">
                            <span class="material-symbols-outlined text-3xl">backup</span>
                        </div>
                        <div>
                            <h3 class="font-bold text-lg">Tạo bản sao lưu mới</h3>
                            <p class="text-indigo-100 text-sm">Backup toàn bộ database</p>
                        </div>
                    </div>
                    <p class="text-indigo-100 text-sm mb-6">
                        Hệ thống sẽ tạo một file .sql chứa toàn bộ cấu trúc và dữ liệu hiện tại. Quá trình này có thể
                        mất vài giây.
                    </p>
                    <form method="POST">
                        <input type="hidden" name="action" value="create_backup">
                        <button type="submit"
                            class="w-full py-3 px-4 bg-white text-indigo-600 font-bold rounded-xl hover:bg-indigo-50 transition-colors shadow-md flex items-center justify-center gap-2">
                            <span class="material-symbols-outlined">add_circle</span>
                            Tạo Backup Ngay
                        </button>
                    </form>
                </div>
            </div>

            <!-- Stats/Info Card -->
            <div class="card">
                <div class="card-header">
                    <h3 class="font-bold text-lg flex items-center gap-2">
                        <span class="material-symbols-outlined">info</span>
                        Thông tin
                    </h3>
                </div>
                <div class="card-body">
                    <ul class="space-y-4">
                        <li class="flex items-start gap-3">
                            <span class="material-symbols-outlined text-gray-400 mt-1">storage</span>
                            <div>
                                <p class="font-semibold text-sm">Vị trí lưu trữ:</p>
                                <code
                                    class="text-xs bg-gray-100 dark:bg-slate-700 px-2 py-1 rounded block mt-1 break-all">admin/backups/</code>
                            </div>
                        </li>
                        <li class="flex items-center gap-3">
                            <span class="material-symbols-outlined text-gray-400">format_list_numbered</span>
                            <div>
                                <p class="font-semibold text-sm">Số lượng bản backup:</p>
                                <p class="text-sm text-gray-500"><?php echo count($backups); ?> bản</p>
                            </div>
                        </li>
                        <li class="flex items-center gap-3">
                            <span class="material-symbols-outlined text-gray-400">hard_drive</span>
                            <div>
                                <p class="font-semibold text-sm">Tổng dung lượng:</p>
                                <p class="text-sm text-gray-500">
                                    <?php
                                    $total_size = 0;
                                    foreach ($backups as $b)
                                        $total_size += $b['size'];
                                    echo format_size($total_size);
                                    ?>
                                </p>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>

            <!-- Restore Warning -->
            <div class="bg-yellow-50 border border-yellow-200 rounded-xl p-4">
                <div class="flex items-start gap-3">
                    <span class="material-symbols-outlined text-yellow-600">warning</span>
                    <div>
                        <h4 class="font-bold text-yellow-800 text-sm">Lưu ý khi Restore</h4>
                        <p class="text-xs text-yellow-700 mt-1">
                            Khi restore, toàn bộ dữ liệu hiện tại sẽ bị xóa và thay thế bằng dữ liệu trong bản backup.
                            Hãy chắc chắn rằng bạn đã backup dữ liệu hiện tại trước khi restore phiên bản cũ.
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <!-- Right Column: Backup List -->
        <div class="lg:col-span-2">
            <div class="card">
                <div
                    class="card-header border-b border-gray-100 dark:border-slate-700 flex justify-between items-center">
                    <h3 class="font-bold text-lg flex items-center gap-2">
                        <span class="material-symbols-outlined text-gray-500">history</span>
                        Lịch sử Backup
                    </h3>
                </div>

                <?php if (empty($backups)): ?>
                    <div class="p-12 text-center text-gray-500">
                        <span class="material-symbols-outlined text-6xl text-gray-300 mb-4">folder_off</span>
                        <p>Chưa có bản backup nào.</p>
                        <p class="text-sm mt-2">Nhấn "Tạo Backup Ngay" để tạo bản sao lưu đầu tiên.</p>
                    </div>
                <?php else: ?>
                    <div class="overflow-x-auto">
                        <table class="w-full text-left border-collapse">
                            <thead>
                                <tr
                                    class="bg-gray-50 dark:bg-slate-800 text-gray-500 dark:text-gray-400 text-xs uppercase tracking-wider">
                                    <th class="p-4 font-semibold">Tên File</th>
                                    <th class="p-4 font-semibold">Ngày tạo</th>
                                    <th class="p-4 font-semibold">Kích thước</th>
                                    <th class="p-4 font-semibold text-right">Hành động</th>
                                </tr>
                            </thead>
                            <tbody class="divide-y divide-gray-100 dark:divide-slate-700">
                                <?php foreach ($backups as $backup): ?>
                                    <tr class="hover:bg-gray-50 dark:hover:bg-slate-800/50 transition-colors group">
                                        <td class="p-4">
                                            <div class="flex items-center gap-3">
                                                <span class="material-symbols-outlined text-[#d4af37]">description</span>
                                                <span
                                                    class="font-medium text-gray-700 dark:text-gray-200"><?php echo htmlspecialchars($backup['name']); ?></span>
                                            </div>
                                        </td>
                                        <td class="p-4 text-sm text-gray-500">
                                            <?php echo date('d/m/Y H:i:s', $backup['date']); ?>
                                            <div class="text-xs text-gray-400"><?php echo date('l', $backup['date']); ?></div>
                                        </td>
                                        <td class="p-4 text-sm text-gray-500 font-mono">
                                            <?php echo format_size($backup['size']); ?>
                                        </td>
                                        <td class="p-4 text-right">
                                            <div class="flex items-center justify-end gap-2">
                                                <!-- Download -->
                                                <a href="?download=<?php echo urlencode($backup['name']); ?>"
                                                    class="p-2 text-blue-600 hover:bg-blue-50 rounded-lg tooltip-container"
                                                    title="Tải xuống">
                                                    <span class="material-symbols-outlined text-xl">download</span>
                                                </a>

                                                <!-- Restore -->
                                                <form method="POST" class="inline-block"
                                                    onsubmit="return confirm('⚠️ CẢNH BÁO: Hành động này sẽ ghi đè toàn bộ database hiện tại!\n\nBạn có chắc chắn muốn restore từ file <?php echo $backup['name']; ?> không?');">
                                                    <input type="hidden" name="action" value="restore_backup">
                                                    <input type="hidden" name="filename"
                                                        value="<?php echo htmlspecialchars($backup['name']); ?>">
                                                    <button type="submit"
                                                        class="p-2 text-green-600 hover:bg-green-50 rounded-lg tooltip-container"
                                                        title="Phục hồi dữ liệu">
                                                        <span class="material-symbols-outlined text-xl">restore</span>
                                                    </button>
                                                </form>

                                                <!-- Delete -->
                                                <form method="POST" class="inline-block"
                                                    onsubmit="return confirm('Bạn có chắc chắn muốn xóa file backup này không?');">
                                                    <input type="hidden" name="action" value="delete_backup">
                                                    <input type="hidden" name="filename"
                                                        value="<?php echo htmlspecialchars($backup['name']); ?>">
                                                    <button type="submit"
                                                        class="p-2 text-red-600 hover:bg-red-50 rounded-lg tooltip-container"
                                                        title="Xóa bản backup">
                                                        <span class="material-symbols-outlined text-xl">delete</span>
                                                    </button>
                                                </form>
                                            </div>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<?php include 'includes/admin-footer.php'; ?>